export interface TradingComments {
    generalObservations: string[];
    recommendations: string[];
}

export interface LiveChecklistItem {
    status: "safe" | "warning" | "danger";
    title: string;
    message: string;
}

export interface ApiResponse {
    claudeComments: TradingComments;
    liveExposureChecklist?: LiveChecklistItem[];
}

export type OpenPositionPayload = {
    symbolName: string;
    positionType: "buy" | "sell";
    entryPrice: number;
    markPrice: number | null;
    quantity: number;
    unrealizedPnL: number | null;
    unrealizedPnLPercent: number | null;
    positionValue: number | null;
};

export type PortfolioRiskSummary = {
    totalOpenPositions: number;
    totalPositionValue: number;
    totalUnrealizedPnL: number;
    totalUnrealizedPnLPercent: number;
};

export type AIPayload = {
    openPositions: OpenPositionPayload[];
    portfolioSummary: PortfolioRiskSummary;
    closedTrades: {
        symbolName: string;
        positionType: string;
        openTime: string;
        result: string;
    }[];
};

export interface dialogWindowType {
    type: "user" | "system";
    content: string[];
}

export type ReportType = {
    moneyManagement: dialogWindowType[];
    instruments: dialogWindowType[];
    timeManagement: dialogWindowType[] | null;
    liveExposureChecklist?: LiveChecklistItem[];
    portfolioSummary?: PortfolioRiskSummary | null;
    openPositions?: OpenPositionPayload[] | null;
};

export type autoGeneratedReportType = {
    moneyManagement: string[];
    instruments: string[];
};

export type Category = "moneyManagement" | "instruments" | "timeManagement";

export type ReportsEntry = {
    createdAt: string;
    reportId: string;
    numberOfMessages: number;
    isFavorite: boolean;
};
